### ISSUE TITLE
cant fix it

### ISSUE THREAD

**Issue by shankikoy** [goatcorp/FFXIVQuickLauncher#761] opened 2022-03-13 00:00 UTC
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Util.GetDiskFreeSpace(String path) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Util.cs:line 127
   at XIVLauncher.Common.Game.Patch.PatchManager.<PatchAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__34.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1124

Version: 6.2.17.0
Git Hash: 6.2.17-0-ga3c1ec4
Context: HandlePatchAsync
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

already uninstalled/reinstalled/deleted appdata/reinstalled ff14

**Comment by ApeironTsuka** [comment] 2022-03-13 00:08
Since the above is missing context (though I'm unsure if my identical error is caused by the same underlying problem because of that), I'm throwing my hat in with some extra:
This is happening on Linux with a fresh prefix, using the Lutris script provided [here](https://github.com/ValveSoftware/Proton/issues/580#issuecomment-1065715430) by KernelZechs. It's a modified version of the one on Lutris proper, except adding installing Steam as part of it just to make it easier.

**Comment by ApeironTsuka** [comment] 2022-03-13 19:05
Can confirm this is fixed in 6.2.18, and can be closed.

**Closed** 2022-03-14 01:33 UTC
