### ISSUE TITLE
XIVLauncher issue

### ISSUE THREAD

**Issue by DeusRage** [goatcorp/FFXIVQuickLauncher#1226] opened 2023-01-10 15:21 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

The game updated and I didn't have Dalamud up so I just closed app and tried rebooting it. Then Error. I tried uninstalling the launcher and reinstalling it and same issue.

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:D2021.11.27.0000.0001.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 405

Version: 6.3.1.0
Git Hash: 6.3.1-0-g989c891
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment] 2023-01-10 15:23
Duplicate of https://github.com/goatcorp/FFXIVQuickLauncher/issues/1225

**Closed by NotNite** 2023-01-10 15:23 UTC
Labels: bug, triage
