### ISSUE TITLE
Error on log in

### ISSUE THREAD

**Issue by dasdfasfa** [goatcorp/FFXIVQuickLauncher#1549] opened 2024-06-27 23:41 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hello I am just trying to update my game before early access and i am getting this error on log in.
I just checked the discord and you guys said I can use the launcher to update my game.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---

### Platform

Windows

**Comment by NotNite** [comment] 2024-06-27 23:41
Duplicate of #1537.

**Closed by NotNite** 2024-06-27 23:41 UTC
Labels: bug, triage

**Comment by dasdfasfa** [comment] 2024-06-27 23:50
Just so im not confused, pre ordering dawntrail includes a 30 day sub correct?

**Comment by reiichi001** [comment] 2024-06-27 23:51
> Just so im not confused, pre ordering dawntrail includes a 30 day sub correct?

Expansions do not include game time. The only purchase that does that is the base game (Starter / Complete editions)
