### ISSUE TITLE
Error at log in - opensuse tumbleweed

### ISSUE THREAD

**Issue by papaskydragon** [goatcorp/FFXIVQuickLauncher#401] opened 2021-03-13 03:03 UTC
Hello,

After making a clean install through the Lutris script, I get this error after clicking 'Log in'. Game is installed through Steam.

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 136
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 514
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.3.7.0
Git Hash: e4f8d3a
Context: Login
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: Z:\home\papaskydragon\.local\share\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by reiichi001** [comment] 2021-03-13 03:11
Duplicate of #360.

You will need to set a dssenh override to native for wine to use the correct TLS version.

In your Lutris environment variable settings for FFXIV, please add `dssenh` and set it to `n`

**Comment by papaskydragon** [comment] 2021-03-13 12:12
Hello again,

> In your Lutris environment variable settings for FFXIV, please add `dssenh` and set it to `n`

I did this to no avail: I still get the same error. Is there anything else I can try?

**Comment by reiichi001** [comment] 2021-03-13 14:36
This is much easier troubleshot in the xivlauncher discord. Preferably, ping me there (I'm Franz Renatus#1846 there).

If you were setting the override in winecfg instead of Lutris, I've got a report that that does not work. You do want to do it directly in Lutris (or set the appropriate environment variable yourself).

![image](https://user-images.githubusercontent.com/10376708/111033483-4e93bb80-83c6-11eb-9247-acbb3d32b328.png)

Failing that, you'd need to enable TLS 1.0 and 1.1 support on your distro, which is not something we can help you do.

**Comment by papaskydragon** [comment] 2021-03-14 19:55
Hi again,

I had already done that in the right place, I checked your reply on [#360](https://github.com/goatcorp/FFXIVQuickLauncher/issues/360).

I eventually got it working today: apparently, I was using an old version of Lutris' wine with the launcher; changed it to Staging and now it works perfectly.

Thank you for your help and time.

**Comment by goaaats** [comment] 2021-06-11 12:33
This seems to be solved. Thank you.

**Closed by goaaats** 2021-06-11 12:33 UTC
