### ISSUE TITLE
Unexpected error.

### ISSUE THREAD

**Issue by Blood-Tear-8** [goatcorp/FFXIVQuickLauncher#1414] opened 2023-10-31 20:32 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Ran a -Repair game files- after game had crashed.

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 448
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 282
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 634

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
```

**Comment by reiichi001** [comment] 2023-10-31 22:32
Repair indexes were not available at the time you tried to run one. Duplicate of #1415.

They are available now, and you should be able to run a repair if you want/need to. If it errors out after that, please open a new issue.

**Closed by reiichi001** 2023-10-31 22:32 UTC
Labels: bug, triage
