### ISSUE TITLE
ff14 launcher erro

### ISSUE THREAD

**Issue by Viperfearne** [goatcorp/FFXIVQuickLauncher#1416] opened 2023-10-31 22:27 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

i just loged into the launcher like normal after the big update

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:D2023.09.23.0000.0001.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 418

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by reiichi001** [comment] 2023-10-31 22:34
Duplicate of #1415. A repair was run before the indexes were available. They've been added recently, so relaunching and acquiring them should allow you to run a repair now if you need to.

**Closed by reiichi001** 2023-10-31 22:34 UTC
Labels: bug, triage

**Comment by Viperfearne** [comment] 2023-10-31 22:36
i need help with this very unsure what i have to do but it seams i cannot start ganme through this launcher

**Comment by Viperfearne** [comment] 2023-10-31 22:39
now i get this when i try to launch
System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 448
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 282
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 634

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment] 2023-10-31 22:44
Please open a new issue and attach the full launcher log. 

You'll find it in `%appdata%\xivlauncher` named `output.log`
