### ISSUE TITLE
2 parts - Squirrel updates hang forever if github is down; a failed update check will kill the launcher

### ISSUE THREAD

**Issue by ff-meli** [goatcorp/FFXIVQuickLauncher#207] opened 2020-04-02 21:31 UTC
**Describe the bug here:**

2 related issues:
* When github is having connectivity issues (as it has been intermittently today and before), the update check in XL seemingly never completes, even to error out.
* If the update check fails for any reason, XL will just quit immediately rather than just letting the user login with the old launcher.

**Steps to reproduce the bug:**
1. Wait for github to die :p
2. Run the launcher
3. Cry as it hangs forever OR
4. Cry as it quits due to an error, rather than just letting me play the game

**Expected behavior**
I would expect the update check to time out benignly after a short wait, and allow the user to attempt to launch the game with the existing version (which may well be the most recent anyway).  Maybe a warning dialog would make sense.

Similarly, if an actual error occurs during update checking, I would expect this to not be a fatal problem, and I should be allowed to continue trying to launch the game, again maybe with a warning dialog.

**Other information (*please* complete the following information):**
Sorry, Aida, none of it is relevant :D

**Comment by goaaats** [comment] 2020-04-03 03:25
So intended behavior is that XL doesn't start if it can't check for updates. I decided on that long ago because I had some issues with people using really old versions.

However, what should happen in that case is an exception window being shown and the app being quit after. I will fix that.

Having it start the original launcher in these cases is a neat idea that I'll look into.

**Comment by rcdailey** [comment] 2020-05-07 23:20
Before opening a new bug I want to confirm if the error I'm getting is the same issue. Here is the stack trace I get in a message box:

![image](https://user-images.githubusercontent.com/1768054/81353712-65270300-908f-11ea-97f5-b269087341f8.png)

**Comment by Zyian** [comment] 2020-07-27 19:58
What are the thoughts on mirroring releases to GitLab, I know of the thoughts on ways to avoid hosting in S3 or other cloud services, but if there was a mirror in GitLab (like upload through an action) then have the updater fall back to the GitLab releases it may cushion the pain here

**Comment by chengyuhui** [comment] 2020-08-26 01:26
My suggestion is that we can use services such as GitHub Pages to host files required for update checking, as these services have a stronger CDN and relaxed limits. The GitHub API is not really intended for end users to call frequently as we have a (relatively) large user base.

**Comment by chengyuhui** [comment] 2020-09-07 15:14
Just discovered that there is a `ReleaseNoUpdate` variant, which disables this nuisance.

**Comment by goaaats** [comment] 2020-09-07 15:16
I'll move to S3 soon, either on GCP or on DigitalOcean.

**Comment by goaaats** [comment] 2021-06-11 12:40
We're now tracking a Squirrel replacement in #445, so I'm closing this for now.

**Closed by goaaats** 2021-06-11 12:40 UTC
Labels: bug, confirmed, enhancement
