### ISSUE TITLE
Update game error

### ISSUE THREAD

**Issue by NLDGreen** [goatcorp/FFXIVQuickLauncher#287] opened 2020-10-13 14:18 UTC
Was trying to update my game to 5.35 when I keep getting this error in XIVLauncher

System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchInstaller.cs:line 48
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 127
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 484
Version: 5.1.1.0
Git Hash: 807acc0
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: C:\Users\Nicholas\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by goaaats** [comment] 2020-10-29 13:29
This is a duplicate of #230

**Closed by goaaats** 2020-10-29 13:29 UTC
