### ISSUE TITLE
Impossible to update game after identification

### ISSUE THREAD

**Issue by Suranovi** [goatcorp/FFXIVQuickLauncher#466] opened 2021-07-03 04:28 UTC
This a fresh new install of openSuse Tumbleweed. I added the openssl package with no success.

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 400
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 0
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__18.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 557
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 400
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.5.8.0
Git Hash: 5.5.8-0-ge76118e
Context: Login
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: French
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by reiichi001** [comment] 2021-07-03 04:48
Hello!

This issue's cause varies depending on Linux distribution, Wine version, and local config. It's difficult to reproduce because settings and behavior can change outside of our control.

Given that this is a fresh install, am I safe to assume you're using the most recent Lutris installer for XIVLauncher and that the wine prefix was not copied from another machine?

For most distributions, we add an environment variable in Lutris for `dssenh=n` which sets some SSL/TLS settings to use native libraries. In your case, it may help to remove that.

Most likely, you'll need to relax your SSL policies because Square Enix isn't perfect. If you have access to the `update-crypto-policies` tool in your package manager, you could try that. Otherwise, you'll need to adjust the settings yourself.

**Comment by reiichi001** [comment] 2021-11-03 00:15
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) with the current Lutris install script (uses Wine 6.10), please open a new issue and we can help troubleshoot it.

**Closed by reiichi001** 2021-11-03 00:15 UTC
