### ISSUE TITLE
XIVLauncher error

### ISSUE THREAD

**Issue by Cib907** [goatcorp/FFXIVQuickLauncher#1524] opened 2024-06-26 16:16 UTC
### Update disclaimer

- [ ] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I have this error whenever i launch XIVLauncher

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: French
Game path: C:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by ITheSpecterI** [comment] 2024-06-27 08:28
Hey there, might be a stupid question, but do you redeemed your Gametime atm?
I had the same issue and forgot that you cant even patch if you dont have gametime, so this fixed it for me.
greetings, John

**Comment by Cib907** [comment] 2024-06-27 11:50
Hi John

I think that’s where the issue comes from, i can’t resub rn cause the
website is down for maintenance but I’ll try whenever it comes online
again.

Thank you for your help and time :)

Le jeu. 27 juin 2024 à 10:28, ITheSpecterI ***@***.***> a
écrit :

**Comment by NotNite** [comment] 2024-06-27 23:20
Closing as duplicate of #1537.

**Closed by NotNite** 2024-06-27 23:20 UTC
Labels: bug, triage
