### ISSUE TITLE
Can't login using XIVLauncher

### ISSUE THREAD

**Issue by IchanP** [goatcorp/FFXIVQuickLauncher#1534] opened 2024-06-26 23:21 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Context: I had not played since May/April and updated using XIVlauncher

- Open XIVLauncher
- Update
- Press login with prefilled username/password

Problem persists when I attempt to repair gamefiles and I receive the same output.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by tommadness** [comment] 2024-06-26 23:23
You need a paid and active subscription to patch the game files. This is not a new requirement.

**Comment by NotNite** [comment] 2024-06-27 23:20
Closing as duplicate of #1537.

**Closed by NotNite** 2024-06-27 23:20 UTC
Labels: bug, triage

**Comment by OniZagru** [comment] 2024-10-15 15:58
I have a paid sub, and I'm still getting this error.
