### ISSUE TITLE
Hi. I'm having trouble getting an error every time I start FFXIV. * Japanese translation *

### ISSUE THREAD

**Issue by atempHQ** [goatcorp/FFXIVQuickLauncher#299] opened 2020-10-31 14:08 UTC
System.Threading.AbandonedMutexException: 放棄されたミューテックスのため、待機は完了しました。
   場所 System.Threading.WaitHandle.ThrowAbandonedMutexException()
   場所 System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   場所 System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   場所 XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) 場所 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:行 49
   場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   場所 System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.1.1.0
Git Hash: 807acc0
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: Japanese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by goaaats** [comment] 2020-10-31 15:56
This is a duplicate of #285 - working on it, thank you!

**Closed by goaaats** 2020-10-31 15:56 UTC
