### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by Alkeyd** [goatcorp/FFXIVQuickLauncher#985] opened 2022-05-26 03:53 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Started the game with XIV Lacunher

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): O identificador da janela é inválido
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em XIVLauncher.App.DalamudOverlayThreadStart() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:linha 267
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

Version: 6.2.37.0
Git Hash: 6.2.37-0-g3eb94ef
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by reiichi001** [comment] 2022-05-26 03:57
Hello!

Please attach the full `output.log`, `dalamud.injector.log`, and `dalamud.log` files. If any of them do not exist, please let us know which ones, and upload the rest.

**Comment by Alkeyd** [comment] 2022-05-26 04:15
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8776211/output.log)
[dalamud.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8776212/dalamud.log)
[dalamud.injector.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8776213/dalamud.injector.log)

**Comment by NotNite** [comment] 2022-07-23 19:10
Duplicate of #912 (at least, that's the issue I'll track this with).

**Closed by NotNite** 2022-07-23 19:10 UTC
Labels: bug, triage
