### ISSUE TITLE
Post-Patch Error

### ISSUE THREAD

**Issue by FulcrumAgent** [goatcorp/FFXIVQuickLauncher#1522] opened 2024-06-26 14:52 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I started up Dalamud to download the 7.0 patch, but I'm getting an error while all my friends are able to patch. Dalamud itself updated, and I tried reinstalling it and it's still doing it.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Games\Square Enix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by goaaats** [comment] 2024-06-26 14:55
Thanks for the report, I'm aware of this but not 100% sure what causes it. I might be able to fix it by the weekend.

**Comment by FulcrumAgent** [comment] 2024-06-26 15:25
I can help you with that. I went to patch through the regular launcher, and it's telling me my subscription isn't active. I don't know if you can do anything to make this launcher display a message when that happens, but that's the issue.

**Comment by Kameily** [comment] 2024-06-26 15:27
I am also getting the same issue, 

I was able to play during the return campaign no issue, went to preload the patch and was met with this error:

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.

   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301 




Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: E:\Program `Files\FFXIV`


specifically this path does not exist for me

> D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301

**Comment by Macapple96** [comment] 2024-06-26 15:31
> I can help you with that. I went to patch through the regular launcher, and it's telling me my subscription isn't active. I don't know if you can do anything to make this launcher display a message when that happens, but that's the issue.

> ### Relevant log output
> ```shell
> System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---
> 
> 
> Version: 6.4.0.0
> Git Hash: 6.4.0-0-gf7e3cea
> Context: GetLoginFunc/Task
> OS: Microsoft Windows NT 6.2.9200.0
> 64bit? True
> Addons Enabled? True
> Auto Login Enabled? True
> Language: English
> LauncherLanguage: English
> Game path: C:\Games\Square Enix\FINAL FANTASY XIV - A Realm Reborn
> ```

I can confirm this was the case for me. I had the very same error OP reported, but then noticed my sub wasn't active. Renewing my sub made this error disappear. 
Maybe I'm undergoing a mandela effect, but did we require an active sub to patch the game with XIVLauncher before?

**Comment by NostromoTomo** [comment] 2024-06-26 15:52
> > I can help you with that. I went to patch through the regular launcher, and it's telling me my subscription isn't active. I don't know if you can do anything to make this launcher display a message when that happens, but that's the issue.
> 
> > ### Relevant log output
> > ```shell
> > System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
> >    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
> >    --- End of inner exception stack trace ---
> >    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> >    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> >    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
> > ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
> >    at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---
> > 
> > 
> > Version: 6.4.0.0
> > Git Hash: 6.4.0-0-gf7e3cea
> > Context: GetLoginFunc/Task
> > OS: Microsoft Windows NT 6.2.9200.0
> > 64bit? True
> > Addons Enabled? True
> > Auto Login Enabled? True
> > Language: English
> > LauncherLanguage: English
> > Game path: C:\Games\Square Enix\FINAL FANTASY XIV - A Realm Reborn
> > ```
> 
> I can confirm this was the case for me. I had the very same error OP reported, but then noticed _my sub wasn't active_. **Renewing my sub made this error disappear.** Maybe I'm undergoing a mandela effect, but did we require an active sub to patch the game with XIVLauncher before?

I have the same error when trying to login via XIVLauncher and I have an active subscription. Error did not go away even after manually updating via normal FFXIV launcher.

**Comment by FulcrumAgent** [comment] 2024-06-26 15:53
I just got my subscription updated and can now patch, so with both of us having this happen and it clear up on payment, it's definitely something to do with the subscription error the log-in server throws.

**Comment by Kameily** [comment] 2024-06-26 15:55
I am also unsubbed at the moment so that is likely what it is. I was waiting until early access to resub but wanted to get the patch downloaded.

**Comment by ArcaneDisgea** [comment] 2024-06-26 18:08
> I can confirm this was the case for me. I had the very same error OP reported, but then noticed _my sub wasn't active_. **Renewing my sub made this error disappear.** Maybe I'm undergoing a mandela effect, but did we require an active sub to patch the game with XIVLauncher before?

@Macapple96 This is correct. An active sub is required to patch the game.

**Comment by NotNite** [comment] 2024-06-27 23:20
Closing as duplicate of #1537.

**Closed by NotNite** 2024-06-27 23:20 UTC
Labels: bug, triage
