### ISSUE TITLE
FFXIV Login/Repair error on Quicklauncher and original launcher. 

### ISSUE THREAD

**Issue by lichenthropy** [goatcorp/FFXIVQuickLauncher#1230] opened 2023-01-10 20:43 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried a PC reset and repair error is still going. This time, it is telling me I may need to reinstall the game. Additionally, I tried opening hte game on the original launcher but was met with a [30426][19900][193] error code. Should I uninstall and reinstall the game or would that further corrupt?

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:D2021.11.27.0000.0001.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 405

Version: 6.3.1.0
Git Hash: 6.3.1-0-g989c891
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment] 2023-01-10 20:44
Duplicate of #1225

**Closed by NotNite** 2023-01-10 20:44 UTC
Labels: bug, triage
