### ISSUE TITLE
Tried to move the patch download directory, but now it states there is an error.

### ISSUE THREAD

**Issue by GamerOfGlory** [goatcorp/FFXIVQuickLauncher#1540] opened 2024-06-27 01:05 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

The launcher told me thatmy C drive has run out of room, so I had to move my patch information to another disk (I moved it to D drive), because it had more space. I also put my patch download directory to the same location. However, when I tried to log on to redownload the rest of the patch, it gave me this error.

System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>cDisplayClass22_0.<TryLogin>b1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---

Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

I don't know what to do now. Please help me.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>cDisplayClass22_0.<TryLogin>b1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by nathanctech** [comment] 2024-06-27 01:13
See: #1537

**Comment by GamerOfGlory** [comment] 2024-06-27 01:16
Wait, it has nothing to do with me messing up the change in location of my patch files?

But I still have my subscription. I have already paid it at June 10th, and don't need to pay it until Jul 11.

**Comment by NotNite** [comment] 2024-06-27 23:19
Closing as duplicate of #1537. This is the same root cause, but it might also be from incorrect account info.

**Closed by NotNite** 2024-06-27 23:19 UTC
Labels: bug, triage
