### ISSUE TITLE
Unexpected Error Occurred after latest patch update

### ISSUE THREAD

**Issue by Chick3nSpagh3tti** [goatcorp/FFXIVQuickLauncher#1231] opened 2023-01-10 22:34 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I was playing the game and it closed all of a sudden. When trying to do either file verification or repairing game files or even deleting the whole game and reinstalling it. After a while, a message stating that an unexpected error occurred when repairing/ starting the game. This has only happened after patching the game. (I have also removed/deleted plugins as made aware they will not work)
![Screenshot_20230110_023126](https://user-images.githubusercontent.com/122409059/211676360-4ba9f939-3c89-432b-bd9e-b9e704935372.png)
(note: I have downloaded the game on an external hard drive but never had an issue till now)

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 448
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 274
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 626

Version: 6.3.1.0
Git Hash: 6.3.1-0-g989c891
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment] 2023-01-10 22:40
Duplicate of #1224

**Closed by NotNite** 2023-01-10 22:40 UTC
Labels: bug, triage
