### ISSUE TITLE
Object reference not set to an instance of object

### ISSUE THREAD

**Issue by naradream** [goatcorp/FFXIVQuickLauncher#1539] opened 2024-06-27 00:32 UTC
### Update disclaimer

- [ ] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I just tried to log in, and launch xiv and this error keeps popping up. I tried white listing the app through firewall but still nothing

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: Z:\Steam Games\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by tommadness** [comment] 2024-06-27 00:34
You cannot update FFXIV without an active subscription. (Trial users have active trial subscriptions).

If you're getting a NullReferenceException error when trying to patch, please make sure you've got an active subscription on the Mog Station. (Or try logging in with the Official Launcher to patch).

**Comment by NotNite** [comment] 2024-06-27 23:19
Closing as duplicate of #1537.

**Closed by NotNite** 2024-06-27 23:19 UTC
Labels: bug, triage
