### ISSUE TITLE
XIV not launching FFXIV correctly

### ISSUE THREAD

**Issue by shidarin** [goatcorp/FFXIVQuickLauncher#1585] opened 2024-07-18 20:31 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Steam Deck `3.5.19-20240422.1`, native flatpack installed XIVLauncher, v1.1.0

Yesterday, I tried to DC travel and received a server error. I force closed XIV Launcher so I could launch it again.

When I launch XIVLauncher now, it tells me "Ready! press the Steam Button and switch to FFXIV."

The problem? FFXIV isn't listed as an application in the sidebar. If you leave this screen open long enough, the FFXIV title music starts playing- so FFXIV is launched, just impossible to switch to.

I discovered that if I launched the FFXIV Free Trial directly then quit it, subsequent launches of XIVLauncher will now correctly show FFXIV in the sidebar list- but the control scheme is broken with both joysticks operating as mouse. The controller configuration shown in steam for FFXIV is correct, but nothing I do seems to impact it. FFXIV settings are correct.

FFXIV will show in the sidebar when XIVLauncher operates until the next Steam Deck restart, when it stops being able to launch FFXIV correctly.

### Platform

Linux (native)

### Wine/Proton runner version

I am not forcing the use of any specific compatibility layer

### Relevant log output

```shell
Hard to copy and paste from Steam Deck but here's some relevant lines:

INF Starting a session(v1.1.0.0 - 08cc538)
ERR Couldn't init Steam with AppId=312060 (FFXIV Free Trial), trying AppId=39210 (FFXIV Retail)
System.Exception: SteamApi_Init returned false. Steam isn't running, couldn't find Steam... etc
ERR Steam couldn't load
System.Exception: Same as above

Given this log, I'm not actually sure how FFXIV is launching in the background at all!
```

**Comment by brandanbooth** [comment] 2024-07-19 01:17
I'm experiencing a similar issue and can't seem to get the gamepad to work properly. It's registering as a mouse and keyboard instead.

**Comment by shidarin** [comment] 2024-07-19 02:58
I've reinstalled FFXIV. The behavior described above continues.

I discovered that if I execute the workaround with one additional change, the control scheme now works:

After a steam deck restart, launch the FFXIV Trial directly.
Immediately, like within 5 seconds, force quit it with Steam.
XIVLauncher will now launch the game into the steam sidebar correctly, and the controller works...

**Comment by brandanbooth** [comment] 2024-07-19 03:17
I ran the reinstallation of the free trial and troubleshooting tool in the launcher, but it did not fix the controller scheme or the game launching issues.

**Comment by NM787** [comment] 2024-07-19 21:42
> I'm experiencing a similar issue and can't seem to get the gamepad to work properly. It's registering as a mouse and keyboard instead.

I’m experiencing the same exact thing with my Steam deck since this morning. In fact, XIVLauncher would not recognize my installation of the game and would show me the screen “One more thing…” asking me to install FFXIV Free demo. I reinstalled and now it occasionally launches the game, but with controls messed up as described by quote. No changes in settings fixes it. Perhaps the most recent update to the game caused this…?

**Comment by tommadness** [comment] 2024-07-19 21:48
No, Steam seems to have changed how they handle demos and free trial software.

Add `XL_FIRSTRUN=0 ` to the beginning of your XIVLauncher launch args in Steam to bypass the First Time Setup dialog.

**Comment by NM787** [comment] 2024-07-19 23:54
> No, Steam seems to have changed how they handle demos and free trial software.
> 
> Add `XL_FIRSTRUN=0 ` to the beginning of your XIVLauncher launch args in Steam to bypass the First Time Setup dialog.

You’re a life-saver my friend! Thank you *so much* for this! Maybe this is obvious for you, and yet it had me stumped. After adding this to the Launcher launch args, the game loads again and the controls work as intended! 

Now it’s up to me to fix the myriad tweaks I had messed with when trying to get the game and the launcher working again…! At least I had a semi-recent save of my settings on the server…

I still have no idea what caused this, so I’m sure you’re right about Steam changes. In any case, I sure am happy and thankful for your fix! 

I wonder if there’s any long term issue from skipping this step on launch… Anyway, I’ll keep on following the issue here and wherever else it may be mentioned…

**Comment by shidarin** [comment] 2024-07-21 16:51
Unfortunately, `XL_FIRSTRUN=0` does not solve the issue of this bug report, at least. Suspect both NM787 and brandonbooth are experiencing slightly gamepad issues without the added issue of XIVLauncher not launching the game into the sidebar.

**Comment by chriskha** [comment] 2024-07-21 20:13
I am experiencing the exact same issue described in this post. 

After Steam Deck wakes from sleep, running XIVLauncher will start up the game but does not allow switching over to the actual game running. I'm using the Free Trial version.

Restarting the steam deck could not resolve it either.

The workaround seems to temporarily fix it. I executed the steps above to start the trial version and force quit it very quickly. After that, running XIVLauncher allowed me to switch over to the actual game. The problem comes back again after exiting the game.

**Comment by shidarin** [comment] 2024-07-21 21:23
> The problem comes back again after exiting the game.

Yeah it's been inconsistent for me over a few days. It's a good thing my steamdeck is basically a FFXIVdeck, so I can just put the deck to sleep without exiting the game.

**Comment by Hadisson** [comment] 2024-07-23 12:10
> Add `XL_FIRSTRUN=0 ` to the beginning of your XIVLauncher launch args in Steam to bypass the First Time Setup dialog.

Hi there.
Just sign-in to say THANK YOU cause i've been search during 2 days within thind a solution. It works perfectly, thank's again.

**Comment by sudocurse** [comment] 2024-07-31 05:40
> The workaround seems to temporarily fix it. I executed the steps above to start the trial version and force quit it very quickly. After that, running XIVLauncher allowed me to switch over to the actual game. The problem comes back again after exiting the game.

experiencing the same, `XL_FIRSTRUN` didn't help until I ran the trial and jumped back in. Any ideas as to why this workaround would work?

**Comment by Alaric323** [comment] 2024-08-11 03:39
I'm getting a very similar issue on a BazziteOS Legion Go.  This is my first time trying to run it on the legion (but not the first time with XIVLauncher in Linux).  I have the free trial installed on Steam, and running XIVLauncher also runs the free trial according to Steam.  But when I try to log in I get "could not get STORED".  Previous reports of this error have said its a serverside issue for Steam to XIV communications.  The game DOES run without "Use steam service" enabled, but I don't get controls working in the same way a steam deck doesn't.

**Comment by brandanbooth** [comment] 2024-08-11 04:29
It looks like my game will launch but my controller schemes not loading in

**Comment by brandanbooth** [comment] 2024-08-11 04:29
So we were back to square one on this

**Comment by shidarin** [comment] 2024-08-12 16:11
> So we were back to square one on this

Hi @brandanbooth I would recommend creating a new ticket for that issue, since it's markedly different than the issue you are posting on.

**Comment by submatrix** [comment] 2024-10-06 01:43
Tried installing XIVLauncher on my Deck for the first time and ran into this issue. Many of the examples here seem to be on the free trial. I am on a Windows license of the game, but the symptoms are the same. XIVLauncher appears to launch FFXIV in the background (I can hear the game audio) but I am unable to switch to it as it is not shown as a running app in the Steam sidebar. Instead, all I see is the screen where XIVLauncher instructs me to switch to FFXIV.

**Comment by reiichi001** [comment] 2024-10-06 02:44
Behind the scenes, @Blooym has been working on <https://github.com/Blooym/xlm> as a better means of getting XIVLauncher set up for Steam-based systems (including the Steam Deck). 

It should also be noted that XIVLauncher for Linux is actually <https://github.com/goatcorp/XIVLauncher.Core>. This repository is for the Windows version of XIVLauncher. (The options for bug reports here are more of a legacy thing before xlcore was separated into its own repository and for when we used to provide a Lutris script to install the Windows version.)

I will be closing this issue, but it can be remade on the xlcore repository if it's still present, or if it still happens when using xlm.

**Closed by reiichi001** 2024-10-06 02:44 UTC
Labels: bug, triage
