### ISSUE TITLE
Rate limit of some kind prevents the launcher from running

### ISSUE THREAD

**Issue by chengyuhui** [goatcorp/FFXIVQuickLauncher#267] opened 2020-08-25 15:21 UTC
**Describe the bug here:**
It seems like there is a rate limit on the update checking process, which crashes the launcher.

**Steps to reproduce the bug:**
Just start the launcher, it happens sometime. I don't know if it is specific to my network.

**Expected behavior**
The launcher should be able to complete the checking process successfully (or fail gracefully).

**Screenshots**
![image](https://user-images.githubusercontent.com/1381736/91193085-4f664800-e729-11ea-9f57-36834be063e3.png)
Sorry for the Chinese UI, but the information should be enough.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 2004
  XIVLauncher version: 5.1.1
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: N/A

**Additional information**

**Comment by karashiiro** [comment] 2020-08-25 18:01
Duplicate of #207

**Closed** 2020-09-01 01:00 UTC
