### ISSUE TITLE
Error on log-in

### ISSUE THREAD

**Issue by Nothinghan** [goatcorp/FFXIVQuickLauncher#1112] opened 2022-08-24 00:49 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Just, opened the launcher, Login, Password, one code and crash error.

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): O identificador da janela é inválido
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em XIVLauncher.App.DalamudOverlayThreadStart() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:linha 270
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment] 2022-08-24 00:58
Duplicate of #912.

**Closed by NotNite** 2022-08-24 00:58 UTC
Labels: bug, triage
