### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by NevendyND** [goatcorp/FFXIVQuickLauncher#1134] opened 2022-09-06 12:02 UTC
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hey, I was forwarded here because it seems to be a GUI bug and I should just report it here
https://github.com/karashiiro/SoundSetter/issues/21

This keeps happen on the Plugin "SoundSetter"

its getting fixed when i reinstall xivlauncher, but it happend again.

![unknown](https://user-images.githubusercontent.com/28860034/188628777-74ec7af2-d106-48c9-8773-89a6dc90775c.png)

### Platform

Windows

**Comment by KazDvs** [comment] 2022-09-07 21:31
Just wanted to add that I am also getting the same issue since the most recent update, only seems to be in soundsetter

**Comment by goaaats** [comment] 2022-09-07 21:32
@Soreepeong Would be much appreciated if you could check this one out some time, might be a regression from your crash fix(which did work very well for the people that were crashing), seems like it's the IconButton component that's acting weird and having the caravan icon

**Comment by Soreepeong** [comment] 2022-09-08 01:19
Fixed with https://github.com/karashiiro/SoundSetter/pull/22. The change made to imgui or font sometime before will force all glyph unavailable characters to be displayed, revealing a UI glitch in SoundSetter.

**Closed** 2022-09-08 01:42 UTC
Labels: bug
