### ISSUE TITLE
Mods not loading post update

### ISSUE THREAD

**Issue by lazymetric** [goatcorp/FFXIVQuickLauncher#830] opened 2022-04-12 13:17 UTC
![Screenshot 2022-04-12 091630](https://user-images.githubusercontent.com/103511867/162971056-940bf8ab-e92f-4daf-a0f3-9210f71d9fc9.png)
This error message keeps popping up when i log in game using the custom launcher.

**Comment by wolfcomp** [comment] 2022-04-12 14:30
Duplicate of #815

**Comment by goaaats** [comment] 2022-04-12 15:18
This error should be fixed now, please restart XIVLauncher and update. Mods won't load because they're not updated yet.

**Closed by goaaats** 2022-04-12 15:18 UTC
