### ISSUE TITLE
Launcher is crashing my game constantly

### ISSUE THREAD

**Issue by Glasbo** [goatcorp/FFXIVQuickLauncher#562] opened 2021-10-10 01:12 UTC
Every time I try to do my hair or change my appearance, it crashes. It sometimes crashes 10x an hour. Sometimes it wont crash all day. Sometimes, I leave the game open, and it crashes in the night

**Comment by reiichi001** [comment] 2021-10-10 01:17
Please send us your dalamud.log log file from `%appdata%\XIVLauncher\` 

It's best to just upload/attach the file if you can instead of posting a clipping of it in a comment. Alternatively, you can upload it into our discord in #xivlauncher-issues or #plugin-issues-help and someone can take a look.

DISCLAIMER:This log will contain your computer username. If you're not comfortable posting that here, you can open the file in a text editor to redact that information first (search and replace).

**Comment by reiichi001** [comment] 2021-10-10 10:47
> Could you please NOT use us as your guinea pigs? Logging into FF after a while and I find the /xlplugins window has changed. At the top it says (TESTING). That made my GFX freeze and I have to hard restart the computer. Would it be possible to move all these to some BETA group until you all think it's safe for release....

Plugin testing is something you, the user, had to enable. Dalamud 6 is considered stable and no longer in testing.

The current Dalamud release was also in testing for over a month by multiple users in an "anyone can opt into this" testing period. We felt it was safe for release at that point and so, it was released. Plugin developers had multiple months to get their plugins updated as well.

If you're running into an issue, we'd be more than happy to help you troubleshoot the cause. We will need to see your Dalamud log to determine if you're being affected by something reproducible or unique to your specific computing environment.

**Comment by lunarwinds84** [comment] 2021-10-10 10:51
My dalamud.log is too big to paste anywhere. Do you have any suggestions for that?

I am unable to change anything in /xlplugins as opening it would cause my FFXIV to hang.

**Comment by lunarwinds84** [comment] 2021-10-10 11:32
> We are aware of an issue that some users are experiencing where downloading plugin icons on first load is causing a stuttering issue that never really recovers. That's currently being tracked and investigated in [goatcorp/Dalamud#634](https://github.com/goatcorp/Dalamud/issues/634) as it's an issue with the plugin system, not XIVLauncher itself.

This could be what was causing my issue as this is what I am referring to with /xlplugins

Do I have to leave that plugin listing open for a period of time?

**Comment by lunarwinds84** [comment] 2021-10-10 11:52
> > Do I have to leave that plugin listing open for a period of time?
> 
> No, it should try to pull icons on the first time you load the plugin installer. For most users, it'll quickly grab icons and then cache them, so it doesn't slow anything down. ...but for users who may have some connection issues getting things off of GitHub or Google Compute servers, it can cause some stuttering and may persist even after the window has been closed. It /shouldn't/ occur if the plugin installer window is never opened, but normally, we'd see some connection issues also logged in the Dalamud log, which is what I need to confirm in order to add more information to the associated issue.
> 
> Are you experiencing the issue before using `/xlplugins`? Or only during/after?

Apparently, this is the first time I've seen the plugin icons. I don't remember seeing the icons last week.

**Comment by reiichi001** [comment] 2021-10-10 11:58
> Apparently, this is the first time I've seen the plugin icons. I don't remember seeing the icons last week.

Now those are new! Beginning in September, we opened up testing for Dalamud 6, which is perhaps the largest upgrade and amount of changes to the plugin system. On October 8th, it went public for all users. We wanted to get it finished and stabilized prior to EndWalker to give plugin devs time to get adjusted to the changes and for users to receive the benefits of the new changes. Some are visual, like the revamped plugin installer. Most were more about improving the plugin system internally, as it offers better flexibility to developers and puts plugin development in a better place going forwards.

If you are able to attach your current log, I'd be curious to see if it's noting down and HTTP/webclient issues, as that can help us find the root cause of the stuttering issue and design a solution to prevent it. (It may just be adding a toggle to skip all image downloads)

**Comment by reiichi001** [comment] 2021-11-03 00:20
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue or contact us in discord and we can help troubleshoot it.

**Closed by reiichi001** 2021-11-03 00:20 UTC
